In [1]:
import pandas
import numpy as np
pandas.__version__

'1.2.4'

## Read In Data

In [2]:
# read data from our csv
df = pandas.read_csv('2019-Present.csv')

In [3]:
df.head()

,Establishment ID,Inspection Date,Establishment Name,Establishment Address,Violation Code,Violation Description,Violation Occurences
0,35-046524,1/8/19,565,565 E 2100,4.3.31,In-Use Utensils - Between-Use Storage.,1.0
1,35-046524,1/8/19,565,565 E 2100,4.3.56,Thawing,1.0
2,35-046524,1/8/19,565,565 E 2100,4.4.64,Cutting Surfaces,1.0
3,35-046524,1/8/19,565,565 E 2100,4.4.76*,Manual and Mechanical Warewashing Equipment-Ch...,1.0
4,35-046524,1/8/19,565,565 E 2100,4.4.82*,"Equipment, Food-Contact Surfaces, Nonfood-Cont...",1.0
...,...,...,...,...,...,...,...
158485,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.7.2**,Working Containers-Common Name**,1.0
158486,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.7.19,Other Personal Care Items-Storage,1.0
158487,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.1.3,Food Handler Training,1.0
158488,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,R392-510UICAA,Utah Indoor Clean Air Act,1.0
158489,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.1.4 (ii),Food Safety Manager Registration,1.0

In [4]:
# Fill in NaN values with "N/A"
df = df.fillna("N/A")

## Add Columns to Identify Critical 1 and Critical 2 Violations

In [5]:
# Get the last character in Violation Code string, place into new column Critical Violation 1
# ref: https://stackoverflow.com/questions/52850192/python-extract-last-digit-of-a-string-from-a-pandas-column
df["Critical Violation 1"] = df["Violation Code"].str.strip().str[-1]
# If Critical Violation 1 contains "*", True, otherwise false
# ref: https://stackoverflow.com/questions/31511997/pandas-dataframe-replace-all-values-in-a-column-based-on-condition
df.loc[df["Critical Violation 1"] == "*", 'Critical Violation 1'] = True
df.loc[df["Critical Violation 1"] != True, 'Critical Violation 1'] = False

# Get the last two characters in Violation Code string, place into new column Critical Violation 2
df["Critical Violation 2"] = df["Violation Code"].str[-2:]
# If Critical Violation 2 contains "**", True, otherwise false
df.loc[df["Critical Violation 2"] == "**", 'Critical Violation 2'] = True
df.loc[df["Critical Violation 2"] != True, 'Critical Violation 2'] = False

# If both critical violation 1 and critical violation 2 are true, then it's just a critical 2 violation
df.loc[df['Critical Violation 2'] == True, "Critical Violation 1"] = False

In [6]:
# See the results
df.head()

,Establishment ID,Inspection Date,Establishment Name,Establishment Address,Violation Code,Violation Description,Violation Occurences,Critical Violation 1,Critical Violation 2
0,35-046524,1/8/19,565,565 E 2100,4.3.31,In-Use Utensils - Between-Use Storage.,1.0,False,False
1,35-046524,1/8/19,565,565 E 2100,4.3.56,Thawing,1.0,False,False
2,35-046524,1/8/19,565,565 E 2100,4.4.64,Cutting Surfaces,1.0,False,False
3,35-046524,1/8/19,565,565 E 2100,4.4.76*,Manual and Mechanical Warewashing Equipment-Ch...,1.0,True,False
4,35-046524,1/8/19,565,565 E 2100,4.4.82*,"Equipment, Food-Contact Surfaces, Nonfood-Cont...",1.0,True,False
...,...,...,...,...,...,...,...,...,...
158485,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.7.2**,Working Containers-Common Name**,1.0,False,True
158486,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.7.19,Other Personal Care Items-Storage,1.0,False,False
158487,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.1.3,Food Handler Training,1.0,False,False
158488,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,R392-510UICAA,Utah Indoor Clean Air Act,1.0,False,False
158489,35-063899,8/22/23,ZULU GRILLE,10709 S REDWOOD,4.1.4 (ii),Food Safety Manager Registration,1.0,False,False

## Remove Numerical Identifiers from Restaurant Chains

In [7]:
# Split names that have "#" on "#" and keep only the first string
# ref: https://stackoverflow.com/questions/40705480/python-pandas-remove-everything-after-a-delimiter-in-a-string
df["Establishment Name"] = df["Establishment Name"].str.split('#').str[0]

In [24]:
# see the results, Subway for example
df.loc[df['Establishment Name'] == "SUBWAY"].head()

,Establishment ID,Inspection Date,Establishment Name,Establishment Address,Violation Code,Violation Description,Violation Occurences,Critical Violation 1,Critical Violation 2,Emergency Enforcement Violation,Variance
133048,35-0015876,11/5/19,SUBWAY,1000 S MAIN,4.4.62,Fixed Equipment-Elevation or Sealing,1.0,False,False,False,False
133049,35-0015876,11/5/19,SUBWAY,1000 S MAIN,4.5.26,Using a Handwashing Sink.**,1.0,False,True,False,False
133050,35-0015876,11/5/19,SUBWAY,1000 S MAIN,4.6.49,Using Dressing Rooms and Lockers,1.0,False,False,False,False
133051,35-0015876,11/5/19,SUBWAY,1000 S MAIN,4.7.16,Restriction and Storage*,1.0,True,False,False,False
133052,35-0014316,8/9/19,SUBWAY,11327 S JORDAN,4.6.40,Repairing-Physical Facilities,1.0,False,False,False,False

## Remove Non-Public Establishments

In [9]:
# define what strings to remove
to_remove = "SCHOOL|CENTER|CHILD|LIVING|CORRECTION|ARAMARK|HEALTH|CARE|JAIL|KIDS|ELEMENTARY|DETENTION|FOOD BANK|RECOVERY"
df = df[df["Establishment Name"].str.contains(to_remove)==False]

In [10]:
# see the results, for example, "ABOVE & BEYOND CHILDCARE" is gone
df.loc[df['Establishment Name'] == "ABOVE & BEYOND CHILDCARE"]

Empty DataFrame
Columns: [Establishment ID, Inspection Date, Establishment Name, Establishment Address, Violation Code, Violation Description, Violation Occurences, Critical Violation 1, Critical Violation 2]
Index: []

## Add a Column Specifying 7.4.4 Emergency Enforcement Violations

In [11]:
# # Create a column called Emergency Enforcement Violation, populate with content of Violation Code
df["Emergency Enforcement Violation"] = df["Violation Code"]
# If Emergency Enforcement Violation contains 7.4.4 True, otherwise false
df.loc[df["Violation Code"].str.contains("7.4.4"), "Emergency Enforcement Violation"] = True
df.loc[df["Emergency Enforcement Violation"] != True, "Emergency Enforcement Violation"] = False

<ipython-input-11-fce06911f6a8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Emergency Enforcement Violation"] = df["Violation Code"]
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [25]:
# see the results
df.loc[df['Violation Code'].str.contains("7.4.4")].head()

,Establishment ID,Inspection Date,Establishment Name,Establishment Address,Violation Code,Violation Description,Violation Occurences,Critical Violation 1,Critical Violation 2,Emergency Enforcement Violation,Variance
1951,35-045554,7/8/20,ALPINE MEADOW REAHABILITATION AND NURSING,2520 S REDWOOD,7.4.4 (ii),Summary Permit Suspension - Imminent Health Ha...,1.0,False,False,True,False
2820,35-041669,2/14/19,AMKHA MISKY PERUVIAN SPECIALTIES,215 S 800,7.4.4 (ii),Summary Permit Suspension - Imminent Health Ha...,1.0,False,False,True,False
3205,35-060708,5/4/23,ANTOJITOS EL COLOCHO,4219 W 3500,7.4.4 (ii),Summary Permit Suspension - Imminent Health Ha...,1.0,False,False,True,False
3744,35-042173,6/4/22,APOLLO BURGERS,940 W 1700,7.4.4 (ii),Summary Permit Suspension - Imminent Health Ha...,1.0,False,False,True,False
3962,35-0012368,1/19/23,APPLE SPICE JUNCTION,6520 S 900,7.4.4 (ii),Summary Permit Suspension - Imminent Health Ha...,1.0,False,False,True,False

## Remove Rows Containing Non-Violations or Undefined Violations

In [13]:
# define what strings to remove
to_remove = "R392-100: 5-202.11*|R392-510UICAA"
df = df[df["Violation Code"].str.contains(to_remove)==False]

In [14]:
# remove rows where violation code begins with 0
df = df[df["Violation Code"].str.startswith("0")==False]

In [15]:
# see the results, no violations that begin with 0
df.loc[df['Violation Code'].str.startswith("0")]

Empty DataFrame
Columns: [Establishment ID, Inspection Date, Establishment Name, Establishment Address, Violation Code, Violation Description, Violation Occurences, Critical Violation 1, Critical Violation 2, Emergency Enforcement Violation]
Index: []

In [16]:
# no violations using codes above
df.loc[df['Violation Code'].str.contains("R392")]

Empty DataFrame
Columns: [Establishment ID, Inspection Date, Establishment Name, Establishment Address, Violation Code, Violation Description, Violation Occurences, Critical Violation 1, Critical Violation 2, Emergency Enforcement Violation]
Index: []

## Add a Column Specifying 7.4.2 Variances

In [17]:
# # Create a column called Emergency Enforcement Violation, populate with content of Violation Code
df["Variance"] = df["Violation Code"]
# If Emergency Enforcement Violation contains 7.4.4 True, otherwise false
df.loc[df["Violation Code"].str.contains("7.4.2"), "Variance"] = True
df.loc[df["Variance"] != True, "Variance"] = False

In [26]:
# see the results, variances are now labeled
df.loc[df['Violation Code'].str.contains("7.4.2")].head()

,Establishment ID,Inspection Date,Establishment Name,Establishment Address,Violation Code,Violation Description,Violation Occurences,Critical Violation 1,Critical Violation 2,Emergency Enforcement Violation,Variance
19779,35-051497,6/11/19,CAFE RIO,3585 S 8400,7.4.2 (iii),Conformance With Approved Procedures,1.0,False,False,False,True
53075,35-063219,7/8/21,GOURMANDISE THE BAKERY DOG PATIO,250 S 300,7.4.2 (ii),Documentation of Proposed Variance and Justifi...,1.0,False,False,False,True
55587,35-068491,1/11/23,HALL PASS - DOG PATIO,153 S RIO GRANDE,7.4.2 (iii),Conformance With Approved Procedures,1.0,False,False,False,True
55859,35-055805,10/17/19,HANAPOKE SUGARHOUSE,675 E 2100,7.4.2 (ii),Documentation of Proposed Variance and Justifi...,1.0,False,False,False,True
67620,35-065809,1/27/23,JUICE DRIP,807 E PIONEER,7.4.2 (i),Variances Modifications and Waivers,1.0,False,False,False,True

## Remove Astrisks from Violation Codes

In [27]:
# ref for removing characters:
# https://saturncloud.io/blog/what-is-the-best-way-to-remove-characters-from-a-string-in-pandas/
# https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html
df['Violation Code'] = df['Violation Code'].str.replace('*', '', regex=True)

In [28]:
# see results, astrisks are removed
df.head()

,Establishment ID,Inspection Date,Establishment Name,Establishment Address,Violation Code,Violation Description,Violation Occurences,Critical Violation 1,Critical Violation 2,Emergency Enforcement Violation,Variance
0,35-046524,1/8/19,565,565 E 2100,4.3.31,In-Use Utensils - Between-Use Storage.,1.0,False,False,False,False
1,35-046524,1/8/19,565,565 E 2100,4.3.56,Thawing,1.0,False,False,False,False
2,35-046524,1/8/19,565,565 E 2100,4.4.64,Cutting Surfaces,1.0,False,False,False,False
3,35-046524,1/8/19,565,565 E 2100,4.4.76,Manual and Mechanical Warewashing Equipment-Ch...,1.0,True,False,False,False
4,35-046524,1/8/19,565,565 E 2100,4.4.82,"Equipment, Food-Contact Surfaces, Nonfood-Cont...",1.0,True,False,False,False

## Save Data

In [29]:
# Save as json file
# ref: https://www.geeksforgeeks.org/exporting-pandas-dataframe-to-json-file/
df.to_json('data.json', orient = 'split', compression = 'infer', index = 'true')

In [30]:
# Save as csv
# ref: https://www.geeksforgeeks.org/saving-a-pandas-dataframe-as-a-csv/
df.to_csv('data.csv')